### ISSUE TITLE
Vessek : Glide On Gate/Continuous switch not working as expected?

### ISSUE THREAD

**Issue by n6smith** [modlfo/VultModules#13] opened 2018-02-01 15:01 UTC
Vessek : Setting Glide switch to ONGATE has no effect on when Glide is applied upon receiving Gate via Gate patch point. Glide remains continuous no matter what position switch is in.  User error or bug? MacOS 10.13.2,  VCV Rack v0.5.1

**Comment by n6smith** [comment] 2018-02-01 15:08
Demo patch to show setup and issue
[Vessek Glide issuevcv.vcv.zip](https://github.com/modlfo/VultModules/files/1685995/Vessek.Glide.issuevcv.vcv.zip)

**Comment by modlfo** [comment] 2018-02-01 15:45
I think that the behavior is what I expected but the label is misleading. "ONGATE" should be something like: do not glide at the beginning of the gate, but do glide all other notes. Do you have any recommendation how it should be named to make it more clear?

**Comment by n6smith** [comment] 2018-02-01 16:05
Interesting as I cannot get that to work either. If I send it gates it still glides on every note, irrespective of if there is a gate received or not when in ONGATE setting.  Again, am I missing something here.. as you described the action as no glide upon receiving a gate (though you said the start of a gate.so Im not sure what that means and how that would affect things.) Until I understand how it really works I cannot think of a more suitable description! :)

Here is an example patch with gates being sent out in time with V/OCT so, according to your description..  it should not glide at all as it is receiving gates in NOGATE mode.

**Comment by n6smith** [comment] 2018-02-01 16:13
Just to clarify what I am now expecting.. In ONGATE mode.. when the Vessek receives a gate, it should not glide.. and when it doesn’t receive a gate, it should glide to the next note received.  That doesn’t appear to be the behavior I am seeing. In fact I haven’t managed to find any way of stopping the glide happening at all. With the switch in either position, the behavior seems to be the same, gates or no gates :)

**Comment by modlfo** [comment] 2018-02-01 16:15
This is a small example that should show how it works. One LFO is constantly changing the pitch while the other is triggering gates. In ONGATE, every time there's a rising edge of the gate signal, the oscillator should jump immediately to that pitch. in any other case, the oscillators will approach the input voltage at a rate defined by the GLIDE button position. In ALWAYS, the oscillators should not jump immediately to the input pitch but approach slowly. 

Let me know if it works like that for you. If not, tell me which version of the binaries you are using to check the code.

[glide_example.vcv.zip](https://github.com/modlfo/VultModules/files/1686213/glide_example.vcv.zip)

**Comment by modlfo** [comment] 2018-02-01 16:18
I have to add that the trigger level for the gate is 2V. So the rising edge is considered when the voltage goes from less than 2V to more than 2V. If the voltage does not go below 2V it will not re-trigger.

**Comment by n6smith** [comment] 2018-02-01 16:30
Ok.. that explains it.. Your patch does work. 

So its the voltage (or lack of it) being sent that prevented my examples from working. 

However, I’m my opinion, it would be more practical and useful in more situations..  if it would trigger a no glide when it received any gate signal like from a clock for example (or upon further thought, the opposite would be even more useful.. only trigger a glide upon receiving a clock or other such trigger) ..… if that is possible?

**Comment by modlfo** [comment] 2018-02-01 19:01
I will change the label to NOGATE. The reason why it was designed as it is was because sequencers like Seq-3 and GridSeq are capable of changing a pitch signal.

One way you can achieve what you mention is to instead of using triggers (short gates of 1ms) you use a gate (active until the note is released). In order to convert a trigger to a gate, you can use Spank and set the Attack and Decay to zero, then you can control the length of the gate with the hold parameter.

**Comment by n6smith** [comment] 2018-02-01 19:13
Thanks Leonardo… That's a tip I will try out later today..

As always, I really appreciate your hard work and the useful responses back too….

Cheers!

**Comment by modlfo** [comment] 2018-02-01 19:46
No problem! I'll close this issue.

**Closed as completed by modlfo** 2018-02-01 19:46 UTC
